openapi: 3.0.0
info:
  title: Employee Management
  description: Manages Employees, Managers and their working hours
  version: 1.0.0
servers: 
  - url: http://localhost:8080
paths:
  /employees:
    get:
      summary:  Returns a list of employees
      responses: 
        '200':
          description: Successful operation - a Json array of employees
          content: 
            application/json:
              schema:
                type: object
                properties:
                  employeeList:
                    type: array
                    items:
                      $ref: '#/components/schemas/employee'
    
    post:
      summary: Adds employee
      requestBody:
        required: true
        content: 
          appliction/json:
            schema:
              $ref: '#/components/schemas/employeeRequest'
      responses:
        '200':
          description: employee created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  employeeId:
                    type: string
                    example: 100abc001
  
  /employees/{empId}:
    get:
      summary: Returns employee with the given Id
      parameters:
        - name: empId
          in: path
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Successful operation - employee
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/employee'
    patch:
      summary: Updates emloyee
      parameters:
        - name: empId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content: 
          appliction/json:
            schema:
              $ref: '#/components/schemas/employeeRequest' 
            
      responses:
        '200':
          description: Updated employee successfully 
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/employee'
    delete:
        summary: deletes employee with the given Id
        parameters:
        - name: empId
          in: path
          required: true
          schema:
            type: string
            
        responses:
          '200':
            description: deleted employee successfully
            content: 
              application/json:
                schema:
                  type: string
                  example: Employee 100abc001 deleted from the employee list
                  
  /attendance/{empId}:
    get:
      summary: Returns attendance report for the given employee
      parameters:
        - name: empId
          in: path
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Successful operation - employee hours
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref:  '#/components/schemas/attendance'  
    post:
      summary: Adds attendance record to the given employee
      parameters:
        - name: empId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content: 
          appliction/json:
            schema:
              $ref: '#/components/schemas/attendanceRequest'
      responses:
        '200':
          description: attendance record added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/attendance'
                  
  
  /attendance/{empId}/{month}:
    get:
      summary: Returns worked hours for the given employee
      parameters:
        - name: empId
          in: path
          required: true
          schema:
            type: string
        - name: month
          in: path
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Successful operation - employee hours
          content: 
            application/json:
              schema:
                type: string
                example: Srivatsa worked 160 hours in June 2022
  /employees/{reportsTo}:
    get:
      summary: Returns list of employees under the given manager
      parameters:
        - name: reportsTo
          in: path
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Successful operation - json array of employees
          content: 
            application/json:
              schema:
                type: object
                properties:
                  employeeList:
                    type: array
                    items:
                      $ref: '#/components/schemas/employee'       
  /employees/managers:
    get:
      summary:  Returns a list of managers
      responses: 
        '200':
          description: Successful operation - a Json array of managers
          content: 
            application/json:
              schema:
                type: object
                properties:
                  managerList:
                    type: array
                    items:
                      $ref: '#/components/schemas/manager'
      
components:
  schemas:
    employee:
      type: object
      properties:
        empId:
          type: string
          example: 100abc001
        empName:
          type: string
          example: Srivatsa
        address:
          type: string
          example: Melbourne
        dob:
          type: string
          example: 29/09/1989
        doj:
          type: string
          example: 22/06/2022
        isManager:
          type: boolean
          example: true
        reportsTo:
          type: string
          example: Deepthi
        team:
          type: string
          example: Detective
    employeeRequest:
      type: object
      properties:
        empName:
          type: string
          example: Srivatsa
        address:
          type: string
          example: Melbourne
        dob:
          type: string
          example: 29/09/1989
    attendance:
      type: object
      properties:
        empId:
          type: string
          example: 100abc001
        empName:
          type: string
          example: Srivatsa
        date:
          type: string
          example: 22/06/2022
        checkin:
          type: number
          example: 8.00        
        checkout:
          type: number
          example: 17.00 
        hours:
          type: number
          example: 9
        holidays:
          type: number
          example: 0
    attendanceRequest:
      type: object
      properties:
        empId:
          type: string
          example: 100abc001
        empName:
          type: string
          example: Srivatsa
        date:
          type: string
          example: 22/06/2022
        checkin:
          type: number
          example: 8.00        
        checkout:
          type: number
          example: 17.00 
    manager:
      type: object
      properties:
        empId:
          type: string
          example: 100abc001
        empName:
          type: string
          example: Srivatsa
        team:
          type: string
          example: detective
        

